# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfed87c8afc99053616d71c6bb535a3d800e690ed62f275d2d109d419353e6727d928d9640dc2413253a8de7cc65aaeadee9a3c1bd15eff82f3d6ba902b2218a

test:
  secret_key_base: 79fb2074dbc116e2147fffb74de18fb1214ed388e90516502569fab546a4b71f0eacd7488bdb130ec06040e1e771fb9ee1f439bd87acb1b8c8223bd7ccf1a6ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
